#!/usr/bin/env ruby
###############################################################################
#### INFO ######################################################################
# Sheetocan - tool for timesheet operations.
# (*w) author: nixargh <nixargh@gmail.com>
VERSION = '2.0.2'
#### LICENSE ###################################################################
#Copyright (C) 2014  nixargh <nixargh@gmail.com>
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see http://www.gnu.org/licenses/gpl.html.
#### REQUIRE ###################################################################
require 'optparse'
#### CLASES ####################################################################
class Options

  # Parse command line arguments
  #
  def parse
    options = Hash.new(false)

    OptionParser.new do |params|
      params.banner = "Sheetocan v.#{VERSION}.\nUsage: #{__FILE__} [options]"
      
      params.on_tail("-h", "--help", "show this message") do
        options[:help] = true
        puts params
        exit 0
      end

      params.on("-m", "--month N", Integer, "show time spent at month with number N") do |month|
        options[:month] = month
      end

      params.on("-r", "--report", "show time spent during this day, week and month") do
        options[:report] = true
      end

      params.on("-l", "--teamlead [p|q|t]", String, "show detailed report, time spent on [projects|queues|tickets]") do |items|
        items_a = Array.new 
        items.each_char { |i| items_a.push(i) }
        options[:teamlead] = items_a
      end

      params.on("-T", "--top N", Integer, "show only top N records at detailed (teamlead) report; 0 stands for no limit") do |tl_limit|
        options[:teamlead_limit] = tl_limit
      end

      params.on("-t", "--truncate N", Integer, "do calculations with only last number of lines") do |l_num|
        options[:trunk_to] = l_num
      end

      params.on("-b", "--bubbles F", Float, "show non-working time in current day between first and last time worked", "count only intervals < F") do |bubble_limit|
        options[:bubbles] = bubble_limit
      end

      params.on("-w", "--wmaker", "display output in five lines for Window Maker dock app") do
        options[:wmaker] = true
      end
    end.parse!

    options
  end
end

class TimeSheet
  attr_accessor :trunk_to, :month

  def initialize(ts_file)
    @ts_file = ts_file
    @calendar_file = ['/usr/share/sheetocan/calendar', "#{SCRIPT_DIR}/calendar"]
    @trunk_to = 1000
    t = Time.now
    _, _, _, @day, @month, @year, @wday = t.to_a
    @month if month
  end

  # Create report of time spent at this day, week and month
  #
  def report
    read
    truncate(@trunk_to)
    exit 1 if !validate_list
    return day_spent, week_spent, month_spent
  end

  # Create report with time spent on tickets and projects
  #
  def teamlead
    read
    truncate(@trunk_to)
    exit 1 if !validate_list
    return time_to_tickets, time_to_queues, time_to_projects
  end

  # Only validate timesheet
  #
  def validate
    read
    truncate(@trunk_to)
    exit 1 if !validate_list
  end

  # Return bubbles minutes
  #
  def bubbles(limit)
    if @list.empty?
      raise "No timesheet content found."
    end
    calculate_bubbles(limit)
  end

  # Show number of workhours at month (default is current month)
  #
  def workhours_month(month=@month)
    calendar = read_calendar
    calendar ? calendar[month] : nil
  end

  private

  # Read working hours calendar
  #
  def read_calendar
    calendar_file = find_calendar
    if calendar_file
      calendar = Hash.new
      IO.read(calendar_file).each_line do |line|
        month, work_days = line.split(':')
        calendar[month.to_i] = work_days.to_i
      end
      calendar
    else
      nil
    end
  end

  # Find calendar file
  #
  def find_calendar
    @calendar_file.each do |file|
      return file if File.exist?(file)
    end
    puts "WARNING: Calendar file not found at: #{@calendar_file}."
    nil
  end

  # Read timesheet and convert it to an array of hashes
  #
  def read
    ts = IO.read(@ts_file)
    ts = ts.split("\n")
    line_number = 0
    bad_lines = Array.new

    @list = ts.inject([]) do |ts_table, line|
      skip_line = false
      line_number = line_number + 1

      # Skip empty lines and comments
      if line.empty? || line.index("Revision") || line.index("#") == 0
        next(ts_table)
      end

      ts_hash = Hash.new
      ts_hash[:number] = line_number
      ts_hash[:date], ts_hash[:stime], ts_hash[:etime], ts_hash[:queue], ts_hash[:rt], ts_hash[:desc] = line.split(",")

      # Detect lines with bad separator and make a list
      ts_hash.each_value do |value| 
        if ! value
          bad_lines.push("Bad syntax at line #{line_number}:\n\t#{line}") 
          skip_line = true
          break
        end
      end
      next(ts_table) if skip_line

      # End time 00:00 is also valid and should be equal to 24:00
      ts_hash[:etime] = "24:00" if ts_hash[:etime] == "00:00"
      
      # Go to next line if something except description is empty
      next (ts_table) if ts_hash[:date].empty? || ts_hash[:stime].empty? || ts_hash[:etime].empty? || ts_hash[:queue].empty? || ts_hash[:rt].empty?
      
      ts_hash[:desc] = ts_hash[:desc].delete("\"")
      ts_hash[:year], ts_hash[:month], ts_hash[:day] = ts_hash[:date].split("-")
      ts_hash[:year], ts_hash[:month], ts_hash[:day] = ts_hash[:year].to_i, ts_hash[:month].to_i, ts_hash[:day].to_i
      
      # Extract project from description
      project = ts_hash[:desc].scan(/(^\S+):\s.+$/).first if ts_hash[:desc]
      ts_hash[:project] = project.first.downcase.delete('-') if project

      ts_table << ts_hash
    end

    # Stop processing if lines with bad syntax found
    if ! bad_lines.empty?
      puts bad_lines
      exit 1
    end

    @list.reverse!
  end

  # Truncating list of timesheet lines to speed up calculating
  #
  def truncate(l_num)
    length = @list.length
    @list = @list[0..l_num - 1] if length > l_num
  end

  # Do some validations of lines data
  #
  def validate_list
    list = @list.reverse
    bad_lines = Array.new

    list.each_index do |i|
      cur_line = list[i]

      # Check all parts of date
      year = cur_line[:year]
      year_now = Time.now.year
      bad_lines.push([cur_line[:number], "Bad year: #{year}"]) if year > year_now

      month = cur_line[:month]
      month_now = Time.now.month
      bad_lines.push([cur_line[:number], "Bad month: #{month}"]) if month < 1 || month > 12

      day = cur_line[:day]
      day_now = Time.now.day
      bad_lines.push([cur_line[:number], "Bad day: #{day}"]) if day < 1 || day > 31

      stime = cur_line[:stime]
      bad_lines.push([cur_line[:number], "Bad start time: #{stime}"]) if stime !~ /^([1-9]|[01]\d|2[0-4]):[0-5]\d$/

      etime = cur_line[:etime]
      bad_lines.push([cur_line[:number], "Bad end time: #{etime}"]) if etime !~ /^([1-9]|[01]\d|2[0-4]):[0-5]\d$/

      # Check ticket name format
      rt = cur_line[:rt]
      bad_lines.push([cur_line[:number], "Bad ticket number: #{rt}"]) if rt !~ /^RT\:\d+$/

      # Record lines where end time more or equal to start time
      bad_lines.push([cur_line[:number], "Start time >= than end time"]) if to_m(cur_line[:etime]) <= to_m(cur_line[:stime])

      # Record lines where start time more or equal to end time of previous line
      if i > 0
        pre_line = list[i - 1]
        if cur_line[:year] < pre_line[:year]
          bad_lines.push([cur_line[:number], "Year < than year of previous record"])
        elsif cur_line[:year] == pre_line[:year]
          if cur_line[:month] < pre_line[:month]
            bad_lines.push([cur_line[:number], "Month < than month of previous record"])
          elsif cur_line[:month] == pre_line[:month]
            if cur_line[:day] < pre_line[:day]
              bad_lines.push([cur_line[:number], "Day < than day of previous record"])
            elsif cur_line[:day] == pre_line[:day]
              bad_lines.push([cur_line[:number], "Start time < than end time of previous record"]) if to_m(cur_line[:stime]) < to_m(pre_line[:etime])
            end
          end
        end
      end

    end

    if !bad_lines.empty?
      puts "Failed to validate timesheet with following errors:"
      bad_lines.each do |error|
        puts "\t#{error[0]}: #{error[1]}"
      end

      return false
    end

    return true
  end

  # Calculate free minutes between busy periods during day
  #
  def calculate_bubbles(limit)
    return nil if (!@year && !@month && !@day)

    list = @list.reverse
    free_min = 0

    list.reverse.each_index do |i|
      cur_line = list[i]

      if i > 0
        pre_line = list[i - 1]
        if cur_line[:year] == @year && cur_line[:month] == @month && cur_line[:day] == @day &&
          pre_line[:year] == @year && pre_line[:month] == @month && pre_line[:day] == @day

          minutes = to_m(cur_line[:stime]) - to_m(pre_line[:etime])

          if minutes < limit
            free_min = free_min + minutes
          end
        end
      end
    end     

    free_min
  end

  # Calculate minutes loged today
  #
  def day_spent
    return nil if (!@year && !@month && !@day)
    @list.inject(0) do |t_spent, line|
      if line[:year] == @year && line[:month] == @month && line[:day] == @day
        minutes = to_m(line[:etime]) - to_m(line[:stime])
        t_spent = t_spent + minutes
      else
        next(t_spent)
      end
    end     
  end

  # Calculate minutes loged this week
  #
  def week_spent
    return nil if (!@year && !@month && !@day && !@wday)
    @list.inject(0) do |t_spent, line|
      if line[:year] == @year && line[:month] == @month && line[:day] > (@day - @wday)
        minutes = to_m(line[:etime]) - to_m(line[:stime])
        t_spent = t_spent + minutes
      else
        next(t_spent)
      end
    end     
  end
  
  # Calculate minutes loged this month
  #
  def month_spent
    return nil if (!@year && !@month)
    @list.inject(0) do |t_spent, line|
      if line[:year] == @year && line[:month] == @month
        minutes = to_m(line[:etime]) - to_m(line[:stime])
        t_spent = t_spent + minutes
      else
        next(t_spent)
      end
    end     
  end

  # Create sorted array with monthly tickets and time spent on them
  #
  def time_to_tickets
    time_to('rt')
  end

  # Create sorted array with monthly queues and time spent on them
  #
  def time_to_queues
    time_to('queue')
  end

  # Create sorted array with monthly projects and time spent on them
  #
  def time_to_projects
    time_to('project')
  end

  # Create sorted array with monthly items and time spent on them
  #
  def time_to(item)
    return nil if !@month

    item_symbol = item.to_sym
    items = Hash.new

    @list.each do |line| 
      if line[:month] == @month
        item = line[item_symbol]
        if item
          time = items[item] ? items[item] : 0
          minutes = to_m(line[:etime]) - to_m(line[:stime])
          items[item] = time + minutes
        end
      end
    end

    items.sort_by{|key, value| value }.reverse
  end

  # Convert time (HH:MM 24-h format) to number of minutes
  #
  def to_m(time)
    h, m = time.split(":")
    h.to_i * 60 + m.to_i
  end
end
#### BEGIN ####################################################################

# Remember script's home directory
script_file = File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__
SCRIPT_DIR = File.dirname(script_file)

# Check ruby version
if RUBY_VERSION.delete('.').to_i < 190
  puts("#{RUBY_VERSION} is unsupported. Please use ruby 1.9.0 or newer.")
  exit 1
end

# Display help if no arguments given
ARGV << '-h' if ARGV.empty?
opt = Options.new
options = opt.parse

# Take last unparsed argument as timesheet file
ts = TimeSheet.new(ARGV[-1])

ts.trunk_to = options[:trunk_to] if options[:trunk_to]
ts.month = options[:month] if options[:month]

reported = false

# Display simple statistics
if options[:report]
  puts if reported

  day_spent, week_spent, month_spent = ts.report

  if (hours_to_work = ts.workhours_month)
    work_hours_info = "#{hours_to_work}, #{(month_spent / 60) - hours_to_work}"
  else
    work_hours_info = ''
  end

  bubbles = options[:bubbles] ? " [#{(ts.bubbles(options[:bubbles] * 60) / 60.0).round(2)}]" : nil

  if ! options[:wmaker]
    puts "#{[day_spent, week_spent, month_spent].map!{|time| (time / 60.0).round(2)}.join(', ')} (#{work_hours_info})#{bubbles}"
  else
    puts [day_spent, week_spent, month_spent].map!{|time| (time / 60.0).round(2)}.join("\n") 
    puts work_hours_info
    puts bubbles.delete(" ") if bubbles
  end

  reported = true
end

# Display detailed statistics
if options[:teamlead]
  # Show only top records (10 by default)
  limit = options[:teamlead_limit] || 10

  puts if reported

  tickets, queues, projects = ts.teamlead

  if options[:teamlead].include?('t')
    limit = (tickets.length - 1) if options[:teamlead_limit] == 0
    puts "Hours spent on tickets (top #{limit}):"
    tickets[0..limit - 1].each do |ticket|
      puts sprintf("%-15s %7.2f", ticket[0], (ticket[1]/60.0).round(2))
    end
    options[:teamlead].delete('t')
  end

  if options[:teamlead].include?('q')
    limit = (queues.length - 1) if options[:teamlead_limit] == 0
    puts "\nHours spent on queues (top #{limit}):"
    queues[0..limit - 1].each do |queue|
      puts sprintf("%-15s %7.2f", queue[0], (queue[1]/60.0).round(2))
    end
    options[:teamlead].delete('q')
  end
  
  if options[:teamlead].include?('p')
    limit = (projects.length - 1) if options[:teamlead_limit] == 0
    puts "\nHours spent on projects (top #{limit}):"
    projects[0..limit - 1].each do |project|
      puts sprintf("%-15s %7.2f", project[0], (project[1]/60.0).round(2))
    end
    options[:teamlead].delete('p')
  end
  
  if options[:teamlead].length > 0
    puts "\nUnknown value(s): #{options[:teamlead]}."
    exit 1
  end

  reported = true
end

# Only validate timesheet
if ! reported
  ts.validate
  puts "No errors found."
end

exit 0
